### ISSUE TITLE
macOS链接之后无法使用

### ISSUE THREAD

**Issue by tsunho12** [lightyearvpn/LightyearVPN#1]
如题 
![image](https://user-images.githubusercontent.com/49738894/66312079-829dbe00-e942-11e9-88cd-4281181b677b.png)

**Comment by lightyearvpn** [comment]
你好，能不能在VPN软件里，通过联系客服，提交一下你的问题。这样的话，我们可以获得您客户端的问题报告，看看具体是什么原因。我们用的也是mac系统，但是没有遇到你说的问题。

还请确认第一次下载的时候，输入了正确的系统密码，这样软件才能正常运行。
还可以尝试在个人喜好里，点击重置按钮，然后再试一试连接。

谢谢
