### ISSUE TITLE
开启之后网站无法正常访问报错crbug/1173575, non-JS module files deprecated.

### ISSUE THREAD

**Issue by zhuangyin8** [lightyearvpn/LightyearVPN#11]
<img width="903" alt="Screen Shot 2021-04-24 at 22 51 03" src="https://user-images.githubusercontent.com/20805894/115978836-f222df00-a5b4-11eb-94e9-425d98697c01.png">

**Comment by lightyearvpn** [comment]
非常抱歉给大家带来的不便，我们的服务器连续几天被封锁和攻击，不知道是GFW还是同行的原因。但是我们的团队都在全力抢修，希望能在48个小时之内修复到一个稳定的程度。我们在修复之后，会对所有付费会员赔偿VIP时间，希望您能谅解。
