### ISSUE TITLE
连不上 连不上 连不上

### ISSUE THREAD

**Issue by taohuadao** [lightyearvpn/LightyearVPN#12]
真的是投诉无门

**Comment by lightyearvpn** [comment]
非常抱歉给大家带来的不便，我们的服务器连续几天被封锁和攻击，不知道是GFW还是同行的原因。但是我们的团队都在全力抢修，希望能在48个小时之内修复到一个稳定的程度。我们在修复之后，会对所有付费会员赔偿VIP时间，希望您能谅解。

**Comment by louisleo234** [comment]
一直保持自动升级，3.21版本，现在试了好多站点及模式都不行，除了下面洛杉矶cn2 gia以外的其它站点以外都不能用，我要申请退款。已经发邮件到admin@lightyearvpn.com邮箱
