### ISSUE TITLE
连接不上了，换了7，8个节点也没用

### ISSUE THREAD

**Issue by Mirrorgo** [lightyearvpn/LightyearVPN#13]
如题

**Comment by lightyearvpn** [comment]
非常抱歉给大家带来的不便，我们的服务器连续几天被封锁和攻击，不知道是GFW还是同行的原因。但是我们的团队都在全力抢修，希望能在48个小时之内修复到一个稳定的程度。我们在修复之后，会对所有付费会员赔偿VIP时间，希望您能谅解。
