### ISSUE TITLE
连接不上了，客服也不回应，请注意！！！！！！！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by HATTER-LONG** [lightyearvpn/LightyearVPN#14]
如题

**Comment by lightyearvpn** [comment]
非常抱歉给大家带来的不便，我们的服务器连续几天被封锁和攻击，不知道是GFW还是同行的原因。但是我们的团队都在全力抢修，希望能在48个小时之内修复到一个稳定的程度。我们在修复之后，会对所有付费会员赔偿VIP时间，希望您能谅解。

**Comment by wxy117** [comment]
什么时候能好呀？都几天了

**Comment by xafha** [comment]
已经好几天了，仍旧连接不上，刚刚办了2年的套餐

**Comment by lightyearvpn** [comment]
目前可以先下载最新的电脑版3.1.0，然后连接香港和美国BGP线路，网盘下载 https://lightyear.lanzous.com/b00tu4njg

**Comment by HATTER-LONG** [comment]
当前试用 Ubuntu 与 Iphone 可以正常连接，速度一般，建议提高客服反馈效率，感谢及时修复
