### ISSUE TITLE
vpn已经连续一周无法连接

### ISSUE THREAD

**Issue by xafha** [lightyearvpn/LightyearVPN#15]
你好，刚刚办了2年套餐，已经一周不能连接了，请问什么原因？？能解决吗

**Comment by lightyearvpn** [comment]
您好, 

非常抱歉给您带来的不便，我们的服务器连续几天被封锁和攻击，可能是GFW又高了。但是我们的团队都在全力抢修，希望能在24个小时之内修复到一个稳定的程度。我们在修复之后，会对所有付费会员赔偿VIP时间，希望您能谅解。

目前可以先下载最新的电脑版3.1.0，然后连接香港和美国BGP线路，网盘下载 https://lightyear.lanzous.com/b00tu4njg
