### ISSUE TITLE
还是连接不稳定及连接不上问题

### ISSUE THREAD

**Issue by lemoshu** [lightyearvpn/LightyearVPN#17]
已经过去半个月了，还是连接非常不稳定，导致很多学术活动无法进行。请问什么时候修复或安排退款

**Comment by giftedunicorn** [comment]
你好

我们的客户端升级了，Windows/Macbook/Linux 最新版本为3.1.1 和 Android/IOS 最新版本为2.3.4。请通过光年下载页面https://lightyearapp.live/download 或者网盘 https://lightyear.lanzous.com/b00tu4njg。请下载最新客户端，然后连接线有BGP线路，老版本将无法连接当前的BGP线路。

Windows用户需要注意，请通过控制面板彻底删除老版本，然后再安装新的3.1.1版本。

苹果手机用户还是需要到国外应用商店下载和更新2.3.4版本。
