### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by Jalever** [lightyearvpn/LightyearVPN#18]
目前我的账号所有的账号都连接不上节点，会显示500 Internal Privoxy Error

**Comment by lightyearvpn** [comment]
我们的客户端升级了，Windows/Macbook/Linux 最新版本为3.1.5 和 Android/IOS 最新版本为2.3.5。请通过光年下载页面https://lightyearapp.live/download 或者网盘 https://lightyear.lanzoui.com/b00tu4njg。请下载最新客户端，然后连接线有BGP线路，老版本将无法连接当前的BGP线路。
