### ISSUE TITLE
有人用过这个VPN吗？刚买的VIP所有 节  点 都无法使用，有没有人说下。

### ISSUE THREAD

**Issue by FGH1335** [lightyearvpn/LightyearVPN#4]
有人用过这个VPN吗？刚买的VIP所有节点都无法使用，有没有人说下。

**Comment by lightyearvpn** [comment]
你好，你可以试试下面几个操作，

1. 确认删除 360安全卫 士和 QQ医生 等类似国产流氓软件
2. 试试应用的设置中的重置按钮
3. 确认关闭其他VPN或者浏览器的代理插件，chrome://settings/system 中查找, 比如Shadowsocks VPN 或者 SwitchyOmega之类的插件。
4. 升级到最新版本
5. 在应用设置中选择全局模式试一试
6. 升级 .NET FRAMEWORK 到最新版本
7. 其他浏览器是否正常?

**Comment by lightyearvpn** [comment]
或者试试重新安装

**Comment by zxcasd848955** [comment]
太垃圾了。我的电脑就用不了。客服不理人，还特别拽。直接封了我的VIP账户。别用。

**Comment by lightyearvpn** [comment]
> 太垃圾了。我的电脑就用不了。客服不理人，还特别拽。直接封了我的VIP账户。别用。

你把我们在线客服，管理员，还有github这里骂了个遍，使用非常攻击性的语言，我们怎么帮助你解决问题呢？还没等我们客服反应，就被你骂了，说nmsl。我们可能不能为你提供服务了，我们取消了你的vip而且已经为你退款，希望你不要再使用了。希望你以后使用文明用语

**Comment by zxcasd848955** [comment]
> > 太垃圾了。我的电脑就用不了。客服不理人，还特别拽。直接封了我的VIP账户。别用。
> 
> 你把我们在线客服，管理员，还有github这里骂了个遍，使用非常攻击性的语言，我们怎么帮助你解决问题呢？还没等我们客服反应，就被你骂了，说nmsl。我们可能不能为你提供服务了，我们取消了你的vip而且已经为你退款，希望你不要再使用了。希望你以后使用文明用语
> > 事实就是很难用啊，win10我的确用不了啊。你们也没解决啊？我肯定不会用，这一点请放心。不要搞的跟你是世界上最后一款VPN了行吗？我只是看到你们的营销联盟在网上吹的才用的呢。别脸大了。另外，放下你的高傲。

**Comment by zxcasd848955** [comment]
> > 太垃圾了。我的电脑就用不了。客服不理人，还特别拽。直接封了我的VIP账户。别用。
> 
> 你把我们在线客服，管理员，还有github这里骂了个遍，使用非常攻击性的语言，我们怎么帮助你解决问题呢？还没等我们客服反应，就被你骂了，说nmsl。我们可能不能为你提供服务了，我们取消了你的vip而且已经为你退款，希望你不要再使用了。希望你以后使用文明用语

@lightyearvpn  事实就是很难用啊，win10我的确用不了啊。你们也没解决啊？我肯定不会用，这一点请放心。不要搞的跟你是世界上最后一款VPN了行吗？我只是看到你们的营销联盟在网上吹的才用的呢。别脸大了。另外，放下你的高傲。

**Comment by zxcasd848955** [comment]
> > 太垃圾了。我的电脑就用不了。客服不理人，还特别拽。直接封了我的VIP账户。别用。
> 
> 你把我们在线客服，管理员，还有github这里骂了个遍，使用非常攻击性的语言，我们怎么帮助你解决问题呢？还没等我们客服反应，就被你骂了，说nmsl。我们可能不能为你提供服务了，我们取消了你的vip而且已经为你退款，希望你不要再使用了。希望你以后使用文明用语

@lightyearvpn 用了这个VPN，我仿佛沾上了一坨💩
