### ISSUE TITLE
iOS 版的 Auto Mode 会将 Bilibili 走代理

### ISSUE THREAD

**Issue by YimianDai** [lightyearvpn/LightyearVPN#8]
Bilibili 是非常常用的 APP 了，但我发现至少在 iOS 版的 APP 上，Auto Mode （确认是 Auto Mode，非 Global Mode）每次 B 站的流量都是会走代理的。

希望能够更新下 Auto Mode，至少让 B 站还是走国内流量。

**Comment by lightyearvpn** [comment]
下次更新会在iOS中加入GFWLIST模式和绕过中国模式，并且升级现有规则
